// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistema_vendas_web.Data;

namespace sistema_vendas_web.Migrations
{
    [DbContext(typeof(VendasContext))]
    [Migration("20191231011705_InitialCreateV1")]
    partial class InitialCreateV1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("sistema_vendas_web.Models.Cliente.Fisico", b =>
                {
                    b.Property<int>("COD_CLIENTE")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("COD_CLIENTE")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BAIRRO")
                        .IsRequired()
                        .HasColumnName("BAIRRO")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnName("CEP")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("CIDADE")
                        .IsRequired()
                        .HasColumnName("CIDADE")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("COMPLEMENTO")
                        .HasColumnName("COMPLEMENTO")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnName("CPF")
                        .HasColumnType("varchar(11)")
                        .HasMaxLength(11);

                    b.Property<DateTime>("DATA_CADASTRO")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DATA_NASCIMENTO")
                        .HasColumnName("DATA_NASCIMENTO")
                        .HasColumnType("date");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnName("EMAIL")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("LOGRADOURO")
                        .IsRequired()
                        .HasColumnName("LOGRADOURO")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasColumnName("NOME")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("NUMERO")
                        .IsRequired()
                        .HasColumnName("NUMERO")
                        .HasColumnType("varchar(4)");

                    b.Property<string>("RG")
                        .HasColumnName("RG")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasColumnName("STATUS")
                        .HasColumnType("varchar(7)");

                    b.Property<string>("TELEFONE_1")
                        .HasColumnName("TELEFONE_1")
                        .HasColumnType("varchar(14)");

                    b.Property<string>("TELEFONE_2")
                        .HasColumnName("TELEFONE_2")
                        .HasColumnType("varchar(14)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnName("UF")
                        .HasColumnType("varchar(2)");

                    b.HasKey("COD_CLIENTE");

                    b.ToTable("Fisicos");
                });

            modelBuilder.Entity("sistema_vendas_web.Models.Cliente.Juridico", b =>
                {
                    b.Property<int>("COD_CLIENTE")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("COD_CLIENTE")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BAIRRO")
                        .IsRequired()
                        .HasColumnName("BAIRRO")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnName("CEP")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("CIDADE")
                        .IsRequired()
                        .HasColumnName("CIDADE")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnName("CNPJ")
                        .HasColumnType("varchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("COMPLEMENTO")
                        .HasColumnName("COMPLEMENTO")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DATA_CADASTRO")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnName("EMAIL")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("INSCRICAO_ESTADUAL")
                        .HasColumnName("INSCRICAO_ESTADUAL")
                        .HasColumnType("varchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("LOGRADOURO")
                        .IsRequired()
                        .HasColumnName("LOGRADOURO")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("NOME_CONTATO")
                        .IsRequired()
                        .HasColumnName("NOME_CONTATO")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NUMERO")
                        .IsRequired()
                        .HasColumnName("NUMERO")
                        .HasColumnType("varchar(4)");

                    b.Property<string>("RAZAO_SOCIAL")
                        .IsRequired()
                        .HasColumnName("RAZAO_SOCIAL")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasColumnName("STATUS")
                        .HasColumnType("varchar(7)");

                    b.Property<string>("TELEFONE_1")
                        .HasColumnName("TELEFONE_1")
                        .HasColumnType("varchar(14)");

                    b.Property<string>("TELEFONE_2")
                        .HasColumnName("TELEFONE_2")
                        .HasColumnType("varchar(14)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnName("UF")
                        .HasColumnType("varchar(2)");

                    b.HasKey("COD_CLIENTE");

                    b.ToTable("Juridicos");
                });

            modelBuilder.Entity("sistema_vendas_web.Models.ItemNota", b =>
                {
                    b.Property<int>("COD_ITEM")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("COD_ITEM")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("COD_NOTA")
                        .HasColumnName("COD_NOTA")
                        .HasColumnType("int");

                    b.Property<int>("COD_PRODUTO")
                        .HasColumnName("COD_PRODUTO")
                        .HasColumnType("int");

                    b.Property<decimal>("PRECO_UNITARIO")
                        .HasColumnName("PRECO_UNITARIO")
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("QUANTIDADE")
                        .HasColumnName("QUANTIDADE")
                        .HasColumnType("int");

                    b.Property<decimal>("TOTAL")
                        .HasColumnName("TOTAL")
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("COD_ITEM");

                    b.ToTable("ItemNotas");
                });

            modelBuilder.Entity("sistema_vendas_web.Models.ItemPedido", b =>
                {
                    b.Property<int>("COD_ITEM")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("COD_ITEM")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("COD_PEDIDO")
                        .HasColumnName("COD_PEDIDO")
                        .HasColumnType("int");

                    b.Property<int>("COD_PRODUTO")
                        .HasColumnName("COD_PRODUTO")
                        .HasColumnType("int");

                    b.Property<decimal>("PRECO_UNITARIO")
                        .HasColumnName("PRECO_UNITARIO")
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("QUANTIDADE")
                        .HasColumnName("QUANTIDADE")
                        .HasColumnType("int");

                    b.Property<decimal>("TOTAL")
                        .HasColumnName("TOTAL")
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("COD_ITEM");

                    b.ToTable("ItemPedidos");
                });

            modelBuilder.Entity("sistema_vendas_web.Models.NotaFiscal", b =>
                {
                    b.Property<int>("NUM_NOTA")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("NUM_NOTA")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BAIRRO")
                        .IsRequired()
                        .HasColumnName("BAIRRO")
                        .HasColumnType("varchar(25)");

                    b.Property<decimal>("BASE_ICMS")
                        .HasColumnName("BASE_ICMS")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("BASE_ICMS_ST")
                        .HasColumnName("BASE_ICMS_ST")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnName("CEP")
                        .HasColumnType("varchar(8)");

                    b.Property<int>("CHAVE_ACESSO")
                        .HasColumnName("CHAVE_ACESSO")
                        .HasColumnType("int");

                    b.Property<string>("CIDADE")
                        .IsRequired()
                        .HasColumnName("CIDADE")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnName("CNPJ")
                        .HasColumnType("varchar(14)")
                        .HasMaxLength(14);

                    b.Property<int>("COD_CLIENTE")
                        .HasColumnName("COD_CLIENTE")
                        .HasColumnType("int");

                    b.Property<int>("COD_PEDIDO")
                        .HasColumnName("COD_PEDIDO")
                        .HasColumnType("int");

                    b.Property<DateTime>("DATA_EMISSAO")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DATA_ENTRADA")
                        .HasColumnName("DATA_ENTRADA")
                        .HasColumnType("date");

                    b.Property<DateTime>("DATA_SAIDA")
                        .HasColumnName("DATA_SAIDA")
                        .HasColumnType("date");

                    b.Property<decimal>("DESCONTO")
                        .HasColumnName("DESCONTO")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("DESPESAS")
                        .HasColumnName("DESPESAS")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("ESPECIE")
                        .IsRequired()
                        .HasColumnName("ESPECIE")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("ESPECIE_CARGA")
                        .IsRequired()
                        .HasColumnName("ESPECIE_CARGA")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("ESPECIE_TRANSPORTADORA")
                        .IsRequired()
                        .HasColumnName("ESPECIE_TRANSPORTADORA")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("FRETE_CONTA")
                        .IsRequired()
                        .HasColumnName("FRETE_CONTA")
                        .HasColumnType("varchar(1)");

                    b.Property<decimal>("FRETE_TRANSPORTADORA")
                        .HasColumnName("FRETE_TRANSPORTADORA")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("INF_COMPLEMENTARES")
                        .HasColumnName("INF_COMPLEMENTARES")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("INSCRICAO_ESTADUAL")
                        .HasColumnName("INSCRICAO_ESTADUAL")
                        .HasColumnType("varchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("LOGRADOURO")
                        .IsRequired()
                        .HasColumnName("LOGRADOURO")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("NATUREZA")
                        .IsRequired()
                        .HasColumnName("NATUREZA")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("NUMERO")
                        .IsRequired()
                        .HasColumnName("NUMERO")
                        .HasColumnType("varchar(4)");

                    b.Property<decimal>("PESO_BRUTO")
                        .HasColumnName("PESO_BRUTO")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("PESO_LIQUIDO")
                        .HasColumnName("PESO_LIQUIDO")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("PLACA_VEICULO")
                        .IsRequired()
                        .HasColumnName("PLACA_VEICULO")
                        .HasColumnType("varchar(8)");

                    b.Property<int>("QTD_CARGA")
                        .HasColumnName("QTD_CARGA")
                        .HasColumnType("int");

                    b.Property<string>("RAZAO_SOCIAL")
                        .IsRequired()
                        .HasColumnName("RAZAO_SOCIAL")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("RESERVADO_FISCO")
                        .HasColumnName("RESERVADO_FISCO")
                        .HasColumnType("varchar(300)");

                    b.Property<int>("SERIE")
                        .HasColumnName("SERIE")
                        .HasColumnType("int");

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasColumnName("STATUS")
                        .HasColumnType("varchar(9)");

                    b.Property<decimal>("SUBTOTAL")
                        .HasColumnName("SUBTOTAL")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("TIPO_CLIENTE")
                        .IsRequired()
                        .HasColumnName("TIPO_CLIENTE")
                        .HasColumnType("varchar(8)");

                    b.Property<decimal>("TOTAL")
                        .HasColumnName("TOTAL")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnName("UF")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UF_VEICULO")
                        .IsRequired()
                        .HasColumnName("UF_VEICULO")
                        .HasColumnType("varchar(2)");

                    b.Property<decimal>("VALOR_COFINS")
                        .HasColumnName("VALOR_COFINS")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("VALOR_FRETE")
                        .HasColumnName("VALOR_FRETE")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("VALOR_ICMS")
                        .HasColumnName("VALOR_ICMS")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("VALOR_ICMS_ST")
                        .HasColumnName("VALOR_ICMS_ST")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("VALOR_IPI")
                        .HasColumnName("VALOR_IPI")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("VALOR_PIS")
                        .HasColumnName("VALOR_PIS")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("VALOR_SEGURO")
                        .HasColumnName("VALOR_SEGURO")
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("NUM_NOTA");

                    b.ToTable("NotaFiscais");
                });

            modelBuilder.Entity("sistema_vendas_web.Models.Pedido", b =>
                {
                    b.Property<int>("COD_PEDIDO")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("COD_PEDIDO")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("COD_CLIENTE")
                        .HasColumnName("COD_CLIENTE")
                        .HasColumnType("int");

                    b.Property<int>("COD_USUARIO")
                        .HasColumnName("COD_USUARIO")
                        .HasColumnType("int");

                    b.Property<DateTime>("DATA_EMISSAO")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DESCONTO")
                        .HasColumnName("DESCONTO")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("FORMA_ENTREGA")
                        .IsRequired()
                        .HasColumnName("FORMA_ENTREGA")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("FORMA_PAGAMENTO")
                        .IsRequired()
                        .HasColumnName("FORMA_PAGAMENTO")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("FRETE")
                        .IsRequired()
                        .HasColumnName("FRETE")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NATUREZA_OPERACAO")
                        .IsRequired()
                        .HasColumnName("NATUREZA_OPERACAO")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("OBSERVACAO")
                        .HasColumnName("OBSERVACAO")
                        .HasColumnType("varchar(180)");

                    b.Property<int>("QTD_PARCELAS")
                        .HasColumnName("QTD_PARCELAS")
                        .HasColumnType("int");

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasColumnName("STATUS")
                        .HasColumnType("varchar(9)");

                    b.Property<decimal>("SUB_TOTAL")
                        .HasColumnName("SUB_TOTAL")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("TABELA_PRECO")
                        .IsRequired()
                        .HasColumnName("TABELA_PRECO")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TIPO_CLIENTE")
                        .IsRequired()
                        .HasColumnName("TIPO_CLIENTE")
                        .HasColumnType("varchar(8)");

                    b.Property<decimal>("TOTAL")
                        .HasColumnName("TOTAL")
                        .HasColumnType("decimal(7,2)");

                    b.Property<int?>("UsuarioCOD_USUARIO")
                        .HasColumnType("int");

                    b.Property<string>("flag_item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("COD_PEDIDO");

                    b.HasIndex("UsuarioCOD_USUARIO");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("sistema_vendas_web.Models.Produto", b =>
                {
                    b.Property<int>("COD_PRODUTO")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("COD_PRODUTO")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ALIQUOTA_IPI")
                        .HasColumnName("ALIQUOTA_IPI")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("COR")
                        .HasColumnName("COR")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DESCRICAO")
                        .IsRequired()
                        .HasColumnName("DESCRICAO")
                        .HasColumnType("varchar(180)");

                    b.Property<int>("QTD_ESTOQUE")
                        .HasColumnName("QTD_ESTOQUE")
                        .HasColumnType("int");

                    b.Property<int>("QTD_MIN_ESTOQUE")
                        .HasColumnName("QTD_MIN_ESTOQUE")
                        .HasColumnType("int");

                    b.Property<int>("QTD_VENDIDA")
                        .HasColumnName("QTD_VENDIDA")
                        .HasColumnType("int");

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasColumnName("STATUS")
                        .HasColumnType("varchar(7)");

                    b.Property<decimal>("TOTAL_VENDIDO")
                        .HasColumnName("TOTAL_VENDIDO")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("UNIDADE_MEDIDA")
                        .HasColumnName("UNIDADE_MEDIDA")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("VALOR_IPI")
                        .HasColumnName("VALOR_IPI")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("VALOR_UNITARIO")
                        .HasColumnName("VALOR_UNITARIO")
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("COD_PRODUTO");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("sistema_vendas_web.Models.Usuario", b =>
                {
                    b.Property<int>("COD_USUARIO")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("COD_USUARIO")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .HasColumnName("CPF")
                        .HasColumnType("varchar(11)")
                        .HasMaxLength(11);

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnName("EMAIL")
                        .HasColumnType("varchar(180)");

                    b.Property<string>("LOGIN")
                        .IsRequired()
                        .HasColumnName("LOGIN")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NIVEL_ACESSO")
                        .IsRequired()
                        .HasColumnName("NIVEL_ACESSO")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasColumnName("NOME")
                        .HasColumnType("varchar(180)");

                    b.Property<string>("SENHA")
                        .IsRequired()
                        .HasColumnName("SENHA")
                        .HasColumnType("varchar(8)")
                        .HasMaxLength(8);

                    b.HasKey("COD_USUARIO");

                    b.HasIndex("CPF")
                        .IsUnique()
                        .HasFilter("[CPF] IS NOT NULL");

                    b.HasIndex("LOGIN")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("sistema_vendas_web.Models.Pedido", b =>
                {
                    b.HasOne("sistema_vendas_web.Models.Usuario", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioCOD_USUARIO");
                });
#pragma warning restore 612, 618
        }
    }
}
